blog/urls.py
from django.urls import path, include

from blog import views

app_name = 'blog'


urlpatterns = [
    path('', views.index, name='home'),
    path('single', views.single, name='single'),
]

projet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

## APPLICATIONS

# 1 Restaurant
# 2 Blog
# 3 Shop

restaurant/urls.py
from django.urls import path, include

from restaurant import views


urlpatterns = [
    path('', views.index, name='home'),
    path('menu', views.menu, name='menu'),
    path('gallery', views.gallery, name='gallery'),
    path('faq', views.faq, name='faq'),
    path('reservation', views.reservation, name='reservation'),
]

shop/urls.py
from django.urls import path, include

from shop import views

app_name = 'shop'


urlpatterns = [
    path('', views.index, name='home'),
    path('single', views.single, name='single'),
    path('cart', views.cart, name='cart'),
]

blog/models.py
from django.db import models

# Create your models here.

restaurant/models.py
from django.db import models
import datetime
from django.utils import timezone
# Create your models here.


# schemas -> relations -> base de donnée -> modéliser php -> requête -> afficher


# schema -> modéliser -> views

class MenuCategory(models.Model):
    titre = models.CharField(max_length=255)

    status = models.BooleanField(default=True)
    date_add = models.DateTimeField(auto_now_add=True)
    date_upd = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Catégorie de menu"
        verbose_name_plural = "Catégories de menu"

    def __str__(self):
        return str(self.titre)


class Ingredient(models.Model):
    titre = models.CharField(max_length=255)

    status = models.BooleanField(default=True)
    date_add = models.DateTimeField(auto_now_add=True)
    date_upd = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Ingredient"
        verbose_name_plural = "Ingredients"

    def __str__(self):
        return str(self.titre)


class Plat(models.Model):
    titre = models.CharField(max_length=255)
    prix = models.IntegerField()
    photo = models.ImageField(upload_to='restaurant/menu/photo', null=True, blank=True)
    categorie = models.ForeignKey('MenuCategory', on_delete=models.CASCADE, related_name='menus')
    ingredients = models.ManyToManyField('Ingredient', related_name='menus')
    isRecommended = models.BooleanField(default=False)

    status = models.BooleanField(default=True)
    date_add = models.DateTimeField(auto_now_add=True)
    date_upd = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Plat"
        verbose_name_plural = "Plats"

    def __str__(self):
        return str(self.titre)

    @property
    def getCategorieTitre(self):
        return self.categorie.titre

    @property
    def getIngredients(self):
        return self.ingredients.filter(status=True)

    @property
    def isNew(self):
        return (timezone.now() - self.date_add) < datetime.timedelta(weeks=1)

    @property
    def pricingTag(self):
        if self.isNew:
            return 'New'
        elif self.isRecommended:
            return 'Recommended'
        else:
            return False

# 1 à 1 : 1 Category < = > 1 plat
# 1 à plusieurs : 1 Category < = > plusieurs plats
# plusieurs à plusieurs: plusieurs Category < = > plusieurs plats

shop/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'pages/blog/blog-carousel.html')


def single(request):
    return render(request, 'pages/blog/blog-single-post.html')

restaurant/views.py
from django.shortcuts import render
from . import models


# Create your views here.

def index(request):
    return render(request, 'pages/home-classic.html')


# ORM filter, all
def menu(request):
    data = {
        'categories': models.MenuCategory.objects.filter(status=True),
        'plats': models.Plat.objects.filter(status=True)
    }
    return render(request, 'pages/menu-board.html', data)


def gallery(request):
    return render(request, 'pages/gallery-grid.html')


def faq(request):
    return render(request, 'pages/faqs.html')


def reservation(request):
    return render(request, 'pages/reservation.html')
# M : Definir le schéma de nos données
# V : Transmition des données et logique de l'application
# T : Logique d'affichage

shop/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'pages/shop/shop.html')


def single(request):
    return render(request, 'pages/shop/shop-single-product.html')


def cart(request):
    return render(request, 'pages/shop/shopping-cart.html')

templates/bases/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <meta name="description" content="Babette">
  <link href="{% static 'images/favicon/favicon.png' %}" rel="icon">
  <title>Babette</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rubik:400,500,700%7cShadows+Into+Light&display=swap">
  <link rel="stylesheet" href="{% static 'css/libraries.css' %}" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body>
  <div class="wrapper">
    <!-- =========================
        Header
    =========================== -->
    <header id="header" class="header header-transparent header-layout4">
      <nav class="navbar navbar-expand-lg sticky-navbar">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'images/logo/logo-light.png' %}" class="logo-light" alt="logo">
            <img src="{% static 'images/logo/logo-dark.png' %}" class="logo-dark" alt="logo">
          </a>
          <button class="navbar-toggler" type="button">
            <span class="menu-lines"><span></span></span>
          </button>
          <div class="collapse navbar-collapse" id="mainNavigation">
            <ul class="navbar-nav ml-auto">
              <li class="nav__item with-dropdown">
                <a href="{% url 'home' %}" class="nav__item-link active">Home</a>
              </li><!-- /.nav-item --><li class="nav__item with-dropdown">
                <a href="{% url 'faq' %}" class="nav__item-link">Faq</a>
              </li><!-- /.nav-item --><li class="nav__item with-dropdown">
                <a href="{% url 'menu' %}" class="nav__item-link">Menu</a>
              </li><!-- /.nav-item --><li class="nav__item with-dropdown">
                <a href="{% url 'gallery' %}" class="nav__item-link">Gallery</a>
              </li><!-- /.nav-item -->
              <li class="nav__item with-dropdown">
                <a href="{% url 'blog:home' %}" class="nav__item-link">Blog</a>
              </li><!-- /.nav-item -->
              <li class="nav__item with-dropdown">
                <a href="{% url 'shop:home' %}" class="nav__item-link">Shop</a>
              </li><!-- /.nav-item -->
              <li class="nav__item with-dropdown">
                <a href="{% url 'reservation' %}" class="nav__item-link active">Réservation</a>
              </li><!-- /.nav-item -->
              <!-- /.nav-item -->
            </ul><!-- /.navbar-nav -->
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
      </nav><!-- /.navabr -->
    </header><!-- /.Header -->

    {% block content %}

    {% endblock %}

    <!-- ========================
      Footer
    ========================== -->
    <footer id="footer" class="footer footer-layout1 text-center bg-dark">
      <div class="footer-inner">
        <div class="container">
          <div class="footer-top">
            <div class="row">
              <div class="col-sm-12 col-md-12 col-lg-12 position-static">
                <svg class="footer__divider-shape" xmlns="http://www.w3.org/2000/svg" width="22" height="61"
                  viewBox="0 0 22 61">
                  <path
                    d="M799,769h2v61h-2V769Zm8,24.8a0.969,0.969,0,0,0-1.911,0,3.012,3.012,0,0,1-.883,2.16,4.486,4.486,0,0,0,0,6.136,3.083,3.083,0,0,1,0,4.32,4.486,4.486,0,0,0,0,6.136,3.088,3.088,0,0,1,0,4.325,4.5,4.5,0,0,0,0,6.142,3.014,3.014,0,0,1,.884,2.163,0.969,0.969,0,0,0,1.911,0,4.414,4.414,0,0,0-1.213-3.07,3.091,3.091,0,0,1,0-4.328,4.491,4.491,0,0,0,0-6.14,3.08,3.08,0,0,1,0-4.319,4.488,4.488,0,0,0,0-6.137,3.081,3.081,0,0,1,0-4.32A4.407,4.407,0,0,0,807,793.8Zm0-20a0.969,0.969,0,0,0-1.911,0,3.014,3.014,0,0,1-.883,2.16,4.486,4.486,0,0,0,0,6.136,3.083,3.083,0,0,1,0,4.32,4.488,4.488,0,0,0,0,6.137,3.087,3.087,0,0,1,0,4.324,4.5,4.5,0,0,0,0,6.142,3.014,3.014,0,0,1,.884,2.163,0.969,0.969,0,0,0,1.911,0,4.414,4.414,0,0,0-1.213-3.07,3.089,3.089,0,0,1,0-4.327,4.491,4.491,0,0,0,0-6.14,3.081,3.081,0,0,1,0-4.32,4.488,4.488,0,0,0,0-6.137,3.081,3.081,0,0,1,0-4.32A4.409,4.409,0,0,0,807,773.8ZM793,793.8a0.969,0.969,0,0,1,1.911,0,3.012,3.012,0,0,0,.883,2.16,4.486,4.486,0,0,1,0,6.136,3.083,3.083,0,0,0,0,4.32,4.486,4.486,0,0,1,0,6.136,3.088,3.088,0,0,0,0,4.325,4.5,4.5,0,0,1,0,6.142,3.014,3.014,0,0,0-.884,2.163,0.969,0.969,0,0,1-1.911,0,4.414,4.414,0,0,1,1.213-3.07,3.091,3.091,0,0,0,0-4.328,4.491,4.491,0,0,1,0-6.14,3.08,3.08,0,0,0,0-4.319,4.488,4.488,0,0,1,0-6.137,3.081,3.081,0,0,0,0-4.32A4.407,4.407,0,0,1,793,793.8Zm0-20a0.969,0.969,0,0,1,1.911,0,3.014,3.014,0,0,0,.883,2.16,4.486,4.486,0,0,1,0,6.136,3.083,3.083,0,0,0,0,4.32,4.488,4.488,0,0,1,0,6.137,3.087,3.087,0,0,0,0,4.324,4.5,4.5,0,0,1,0,6.142,3.014,3.014,0,0,0-.884,2.163,0.969,0.969,0,0,1-1.911,0,4.414,4.414,0,0,1,1.213-3.07,3.089,3.089,0,0,0,0-4.327,4.491,4.491,0,0,1,0-6.14,3.081,3.081,0,0,0,0-4.32,4.488,4.488,0,0,1,0-6.137,3.081,3.081,0,0,0,0-4.32A4.409,4.409,0,0,1,793,773.8Zm-4,5.2h2v41h-2V779Zm20,0h2v41h-2V779Z"
                    transform="translate(-789 -769)"></path>
                </svg>
              </div><!-- /.col-lg-12 -->
              <div class="col-sm-12 col-md-12 col-lg-4">
                <div class="contact-box">
                  <h6 class="contact__box-title">Our Address</h6>
                  <ul class="contact__box-list list-unstyled">
                    <li>22 Alnahas Building, 2 AlBahr St, Tanta Al-Gharbia Governorate, Egypt</li>
                  </ul>
                </div><!-- /.contact-box -->
              </div><!-- /.col-lg-4 -->
              <div class="col-sm-12 col-md-12 col-lg-4">
                <div class="contact-box">
                  <h6 class="contact__box-title">Opening Hours</h6>
                  <ul class="contact__box-list list-unstyled">
                    <li>Mon - Fri: 10 AM - 11 PM</li>
                    <li>Sat - Sun: 9 AM - 1 PM</li>
                  </ul>
                </div><!-- /.contact-box -->
              </div><!-- /.col-lg-4 -->
              <div class="col-sm-12 col-md-12 col-lg-4">
                <div class="contact-box">
                  <h6 class="contact__box-title">Private Dinning</h6>
                  <ul class="contact__box-list list-unstyled">
                    <li><span>Main Email:</span><a href="mailto:Babette@7oroof.com">Babette@7oroof.com</a></li>
                    <li><span>Phone:</span><a href="tel:020101236547">02 0101236547</a></li>
                  </ul>
                </div><!-- /.contact-box -->
              </div><!-- /.col-lg-4 -->
            </div><!-- /.row -->
          </div><!-- /.footer-top -->
          <div class="footer-middle">
            <div class="row">
              <div class="col-sm-12 col-md-12 col-lg-12 position-static">
                <div class="footer__logo-wrap text-center">
                  <img src="{% static 'images/logo/footer-logo.png' %}" alt="logo" class="footer__logo">
                </div>
              </div><!-- /.col-lg-12 -->
            </div><!-- /.row -->
            <div class="row">
              <div class="col-sm-12 col-md-12 col-lg-6 offset-lg-3">
                <p class="mb-20">Babette was designed with the history in mind we have created a soft industrial dining
                  room, combined with an open kitchen, coffee take out bar and alovely awesome on site coffee roastery.
                </p>
                <a href="reservation.html" class="btn btn__primary btn__bordered btn__lg">Book Your Table Now!</a>
              </div><!-- /.col-lg-6 -->
            </div><!-- /.row -->
          </div><!-- /.footer-middle -->
        </div><!-- /.container -->
        <div class="footer-bottom">
          <div class="container">
            <div class="row">
              <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="footer__copyright mb-30">
                  <span>&copy; Babette, With Love by </span>
                  <a href="http://themeforest.net/user/7oroof" class="color-theme">7oroof.com</a>
                </div>
                <ul class="social__icons social__icons-white justify-content-center">
                  <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                  <li><a href="#"><i class="fa fa-tripadvisor"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                </ul><!-- /.social__icons -->
              </div>
            </div><!-- /.row -->
          </div><!-- /.container -->
          <svg class="footer__divider-shape-bottom" xmlns="http://www.w3.org/2000/svg" width="142" height="17"
            viewBox="0 0 142 17">
            <path
              d="M800,600V583c8.782,15.985,46.811,11.315,56,12a35.721,35.721,0,0,1,15,5m-71,0V583c-8.782,15.985-46.811,11.315-56,12a35.717,35.717,0,0,0-15,5"
              transform="translate(-729 -583)"></path>
          </svg>
        </div><!-- /.Footer-bottom -->
      </div><!-- /.Footer-inner -->
    </footer><!-- /.Footer -->
    <button id="scrollTopBtn"><i class="fa fa-angle-up"></i></button>

    <div class="search-popup">
      <i class="fa fa-times close-search"></i>
      <form class="module__search-form">
        <input type="text" class="search__input" placeholder="Type Words Then Enter">
        <button class="module__search-btn"><i class="fa fa-search"></i></button>
      </form>
    </div><!-- /.search-popup -->

  </div>
  <!-- /.wrapper -->

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/plugins.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/pages/blog/blog-carousel.html
{% extends 'bases/base.html' %}
{% load static %}
    {% block content %}
        <!-- ========================
       page title 
    =========================== -->
    <section id="page-title" class="page-title page-title-layout5 text-center bg-overlay bg-overlay-2 bg-parallax">
      <div class="bg-img"><img src="{% static 'images/backgrounds/8.jpg' %}" alt="background"></div>
      <svg class="pagetitle__divider-shape" xmlns="http://www.w3.org/2000/svg" width="22" height="61"
        viewBox="0 0 22 61">
        <path
          d="M799,769h2v61h-2V769Zm8,24.8a0.969,0.969,0,0,0-1.911,0,3.012,3.012,0,0,1-.883,2.16,4.486,4.486,0,0,0,0,6.136,3.083,3.083,0,0,1,0,4.32,4.486,4.486,0,0,0,0,6.136,3.088,3.088,0,0,1,0,4.325,4.5,4.5,0,0,0,0,6.142,3.014,3.014,0,0,1,.884,2.163,0.969,0.969,0,0,0,1.911,0,4.414,4.414,0,0,0-1.213-3.07,3.091,3.091,0,0,1,0-4.328,4.491,4.491,0,0,0,0-6.14,3.08,3.08,0,0,1,0-4.319,4.488,4.488,0,0,0,0-6.137,3.081,3.081,0,0,1,0-4.32A4.407,4.407,0,0,0,807,793.8Zm0-20a0.969,0.969,0,0,0-1.911,0,3.014,3.014,0,0,1-.883,2.16,4.486,4.486,0,0,0,0,6.136,3.083,3.083,0,0,1,0,4.32,4.488,4.488,0,0,0,0,6.137,3.087,3.087,0,0,1,0,4.324,4.5,4.5,0,0,0,0,6.142,3.014,3.014,0,0,1,.884,2.163,0.969,0.969,0,0,0,1.911,0,4.414,4.414,0,0,0-1.213-3.07,3.089,3.089,0,0,1,0-4.327,4.491,4.491,0,0,0,0-6.14,3.081,3.081,0,0,1,0-4.32,4.488,4.488,0,0,0,0-6.137,3.081,3.081,0,0,1,0-4.32A4.409,4.409,0,0,0,807,773.8ZM793,793.8a0.969,0.969,0,0,1,1.911,0,3.012,3.012,0,0,0,.883,2.16,4.486,4.486,0,0,1,0,6.136,3.083,3.083,0,0,0,0,4.32,4.486,4.486,0,0,1,0,6.136,3.088,3.088,0,0,0,0,4.325,4.5,4.5,0,0,1,0,6.142,3.014,3.014,0,0,0-.884,2.163,0.969,0.969,0,0,1-1.911,0,4.414,4.414,0,0,1,1.213-3.07,3.091,3.091,0,0,0,0-4.328,4.491,4.491,0,0,1,0-6.14,3.08,3.08,0,0,0,0-4.319,4.488,4.488,0,0,1,0-6.137,3.081,3.081,0,0,0,0-4.32A4.407,4.407,0,0,1,793,793.8Zm0-20a0.969,0.969,0,0,1,1.911,0,3.014,3.014,0,0,0,.883,2.16,4.486,4.486,0,0,1,0,6.136,3.083,3.083,0,0,0,0,4.32,4.488,4.488,0,0,1,0,6.137,3.087,3.087,0,0,0,0,4.324,4.5,4.5,0,0,1,0,6.142,3.014,3.014,0,0,0-.884,2.163,0.969,0.969,0,0,1-1.911,0,4.414,4.414,0,0,1,1.213-3.07,3.089,3.089,0,0,0,0-4.327,4.491,4.491,0,0,1,0-6.14,3.081,3.081,0,0,0,0-4.32,4.488,4.488,0,0,1,0-6.137,3.081,3.081,0,0,0,0-4.32A4.409,4.409,0,0,1,793,773.8Zm-4,5.2h2v41h-2V779Zm20,0h2v41h-2V779Z"
          transform="translate(-789 -769)"></path>
      </svg>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-12">
            <span class="pagetitle__subheading">Don’t Miss</span>
            <h1 class="pagetitle__heading">Our News</h1>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb justify-content-center">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'blog:home' %}">blog</a></li>
                <li class="breadcrumb-item active" aria-current="page">Carousel</li>
              </ol>
            </nav>
          </div><!-- /.col-lg-12 -->
        </div><!-- /.row -->
      </div><!-- /.container -->
    </section><!-- /.page-title -->

    <!-- ======================
      Blog carousel
    ========================= -->
    <section id="blogCarousel" class="blog blog-carousel pb-60">
      <div class="container">
        <div class="row">
          <!-- Post Item #1 -->
          <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="carousel owl-carousel carousel-dots" data-slide="3" data-slide-md="2" data-slide-sm="1"
              data-autoplay="true" data-nav="false" data-dots="true" data-space="30" data-loop="true" data-speed="700">
              <div class="post-item">
                <div class="post__img">
                  <a href="#">
                    <img src="{% static '/images/blog/grid/1.jpg' %}" alt="post image">
                  </a>
                </div><!-- /.post__img -->
                <div class="post__content">
                  <div class="post__meta">
                    <span class="post__meta-date">Jan 20, 2020</span>
                    <div class="post__meta-cat">
                      <a href="#">Business</a><a href="#">Tips</a>
                    </div><!-- /.post-meta-cat -->
                  </div><!-- /.post-meta -->
                  <h4 class="post__title"><a href="{% url 'blog:single' %}">Simple Recipes for Spring</a></h4>
                  <p class="post__desc">My favorite form of cold-weather exercise is snow-shoeing, but by chance I
                    haven’t
                    been able to go this year. Busy working at the computer when fresh snow fell...</p>
                  <a href="#" class="btn btn__secondary btn__link">Read More</a>
                </div><!-- /.post__content -->
              </div><!-- /.post-item -->
              <!-- Post Item #2 -->
              <div class="post-item">
                <div class="post__img">
                  <a href="#">
                    <img src="{% static 'images/blog/grid/2.jpg' %}" alt="post image">
                  </a>
                </div><!-- /.post__img -->
                <div class="post__content">
                  <div class="post__meta">
                    <span class="post__meta-date">Oct 18, 2020</span>
                    <div class="post__meta-cat">
                      <a href="#">Chef</a><a href="#">Dinner</a>
                    </div><!-- /.post-meta-cat -->
                  </div><!-- /.post-meta -->
                  <h4 class="post__title"><a href="#">Dinner Partty for a Chef!</a></h4>
                  <p class="post__desc">I began my career as a recipe tester for cookbooks, and I did that work for
                    years.
                    We loved cookbooks and loved browsing for them at thrift stores...</p>
                  <a href="#" class="btn btn__secondary btn__link">Read More</a>
                </div><!-- /.post__content -->
              </div><!-- /.post-item -->
              <!-- Post Item #3 -->
              <div class="post-item">
                <div class="post__img">
                  <a href="#">
                    <img src="{% static 'images/blog/grid/3.jpg' %}" alt="post image">
                  </a>
                </div><!-- /.post__img -->
                <div class="post__content">
                  <div class="post__meta">
                    <span class="post__meta-date">Jan 20, 2020</span>
                    <div class="post__meta-cat">
                      <a href="#">Food</a><a href="#">Cheese</a>
                    </div><!-- /.post-meta-cat -->
                  </div><!-- /.post-meta -->
                  <h4 class="post__title"><a href="#">Cake with Cream Cheese</a></h4>
                  <p class="post__desc">I’ve been baking this cake for many years, and have experimented with making it
                    into cupcakes, as a layer cake, serving it dusted with confectioner’s sugar...</p>
                  <a href="#" class="btn btn__secondary btn__link">Read More</a>
                </div><!-- /.post__content -->
              </div><!-- /.post-item -->
              <!-- Post Item #4 -->
              <div class="post-item">
                <div class="post__img">
                  <a href="#">
                    <img src="{% static 'images/blog/grid/4.jpg' %}" alt="post image">
                  </a>
                </div><!-- /.post__img -->
                <div class="post__content">
                  <div class="post__meta">
                    <span class="post__meta-date">Oct 24, 2020</span>
                    <div class="post__meta-cat">
                      <a href="#">Pork</a><a href="#">Belly</a>
                    </div><!-- /.post-meta-cat -->
                  </div><!-- /.post-meta -->
                  <h4 class="post__title"><a href="#">Braised Pork Belly Adobo</a></h4>
                  <p class="post__desc">UX Designer is still a relatively profession, and one that is still being
                    defined.
                    Emilia suggests it is an often...</p>
                  <a href="#" class="btn btn__secondary btn__link">Read More</a>
                </div><!-- /.post__content -->
              </div><!-- /.post-item -->
              <!-- Post Item #5 -->
              <div class="post-item">
                <div class="post__img">
                  <a href="#">
                    <img src="{% static 'images/blog/grid/5.jpg' %}" alt="post image">
                  </a>
                </div><!-- /.post__img -->
                <div class="post__content">
                  <div class="post__meta">
                    <span class="post__meta-date">Oct 27, 2020</span>
                    <div class="post__meta-cat">
                      <a href="#">Apple</a><a href="#">Pie</a>
                    </div><!-- /.post-meta-cat -->
                  </div><!-- /.post-meta -->
                  <h4 class="post__title"><a href="#">Tiny Apple Pies Cinnamon</a></h4>
                  <p class="post__desc">I began my career as a recipe tester for cookbooks, and I did that work for
                    years.
                    We loved cookbooks and loved browsing for them at thrift stores...</p>
                  <a href="#" class="btn btn__secondary btn__link">Read More</a>
                </div><!-- /.post__content -->
              </div><!-- /.post-item -->
              <!-- Post Item #6 -->
              <div class="post-item">
                <div class="post__img">
                  <a href="#">
                    <img src="{% static 'images/blog/grid/6.jpg' %}" alt="post image">
                  </a>
                </div><!-- /.post__img -->
                <div class="post__content">
                  <div class="post__meta">
                    <span class="post__meta-date">Oct 24, 2020</span>
                    <div class="post__meta-cat">
                      <a href="#">Breakfast</a>
                    </div><!-- /.post-meta-cat -->
                  </div><!-- /.post-meta -->
                  <h4 class="post__title"><a href="#">Meal Prep Breakfast Week </a></h4>
                  <p class="post__desc">I’ve been baking this cake for many years, and have experimented with making it
                    into cupcakes, as a layer cake, serving it dusted with confectioner’s sugar...</p>
                  <a href="#" class="btn btn__secondary btn__link">Read More</a>
                </div><!-- /.post__content -->
              </div><!-- /.post-item -->
            </div><!-- /.carousel-->
          </div><!-- /.col-lg-12 -->
        </div><!-- /.row -->
      </div><!-- /.container -->
    </section><!-- /.blog carousel -->
    {% endblock %}
    